REPO_OPTS = ["-strict-sequence"]

REPO_ARCHIVE_OPTS = REPO_OPTS
REPO_EXECUTABLE_OPTS = REPO_OPTS
REPO_INTERFACE_OPTS = REPO_OPTS
REPO_MODULE_OPTS = REPO_OPTS
REPO_NS_MODULE_OPTS = REPO_OPTS

################################################################
## FIXME
SNARKY_OPTS = REPO_OPTS
